module.exports = {
    home: {
        calendar: `📆 Календарь событий`,
        smallGroups: `🏠 Малые Группы`,
        serv: `🙌🏻 Служения`,
        teaching: `📚 Обучение`,
        notes: `🗒 Конспекты`,
        pray: `🙏🏻 Молитвенное`,
        faq: `❔ Вопросы`,
        materialsForSG: `💻 Материалы для МГ`,
    },
    calendar: {
        game: `🎲 Вечер настольных игр`,
        pray: `🙏🏻 Молодежная молитва`,
        turnout: `🏘 Молодежный выезд`,
        goHome: `🌐 Главное меню`,
    },
    smallGroups: {
        sgMember: `🔸Хочу стать участником Малой Группы`,
        sgLeader: `🔸Хочу стать ведущим Малой Группы`,
        sgMap: `🗺 Карта Малых Групп`,
        goHome: `🌐 Главное меню`,
    },
    serv: {
        servAll: `📜 Список служений`,
        servHire: `👀 Мы ищем`,
        servunknown: `🤷🏼 Хочу служить, но не знаю где`,
        goHome: `🌐 Главное меню`,
    }, 
    servAll: {
        servMyGeneration: `💪🏼 Моё Поколение`,
        servWorship: `🎹 Группа Прославления`,
        servInfo: `ℹ️ Стойка Информации`,
        servCafe: `☕️ Служение в кафе`,
        servAsher: `😎 Группа Порядка`,
        servCommunion: `🍷 Служение Причастия`,
        servChild: `👶🏼 Детское служение`,
        servComunication: `🥳 Команда цели Общение`,
        servMeeting: `🤝 Знакомство с Церковью`,
        servSocialWeb: `📱 Соц. сети`,
        backToServ: `Назад к '🙌🏻 Служения'`,
    },
    teaching: {
        onePlusOne: `1 + 1`,
        steps: `🏃🏻‍♂️ Шаги`,
        bibleSchool: `🎓 Библейская Школа`,
        goHome: `🌐 Главное меню`,
    }, 
    onePlusOne: {
        findMentor: `🔎 Хочу найти наставника`,
        becomeMentor: `🎓 Хочу стать наставником`,
        backToTeaching: `Назад к '📚 Обучение'`
    },
    // notes: {},
    // pray: {},
    // faq: {},
    materialsForSG: {
        msgHelp: `📔 Помощь`,
        msgNotes: `🗓 Конспекты`,
        msgWorship: `🎶 Прославление`,
        msgBooks: `📖 Книги`,
        msgVideo: `🟥 Видео-ресурсы`,
        msgMeetings: `🕖 Встречи`,
        goHome: `🌐 Главное меню`,
    },
    // Inline keyboards
    apple: 'Apple',
    google: 'Google',
    appleItemFirst: 'https://calndr.link/e/zugSJAhom2?s=apple',
    appleItemSecond: 'https://calndr.link/e/G4ndn8F16R?s=apple',
    appleItemThird: 'https://calndr.link/e/sQhGjGFwtF?s=apple',
    appleItemFourth: '',
    appleItemFifth: '',
    googleItemFirst: 'https://calndr.link/e/zugSJAhom2?s=google',
    googleItemSecond: 'https://calndr.link/e/G4ndn8F16R?s=google',
    googleItemThird: 'https://calndr.link/e/sQhGjGFwtF?s=google',
    googleItemFourth: '',
    googleItemFifth: '',
}